### ISSUE TITLE
Renewal problem

### ISSUE THREAD

**Issue by japel** [schubergphilis/chef-acme#57]
Hey there, I tried to test the renewal process by specifying
```ruby
node.default['acme']['renew'] = 89
```
The first certificate I got had was issued on:
Monday, 13. February 2017 at 09:52:00
And had an expiry date of:
Sunday, 14. May 2017 at 10:52:00

So I supposed, that if I waited one day, I would get a new certificate, but this did not happen.

Am I getting something wrong, or is this a problem with the renewal process?

Thanks in advance for any help!

japel

**Comment by thoutenbos** [comment]
Hi Japel,

I could imagine it being rounded down in a way. If it still doesn't work after `Wednesday, 15 February 2017 at 10:51:59` then there might be a problem.

Best,
Thijs

**Comment by japel** [comment]
@thoutenbos thanks for the quick reply, I'll take a look tomorrow then.

Best regards

japel

**Comment by japel** [comment]
Sadly no renewal happened 😭 
Is there any logs I could take a look at to gain more information?

**Comment by zurchpet** [comment]
It looks like the recepie has to be run to get a renewed certificate.
Is there a way to have a cron job doing the renewal?

**Comment by japel** [comment]
@zurchpet oh, that would explain why it did not happen on my case

**Comment by jldugger** [comment]
@japel To clarify, are you not running chef-client on a regular basis on the server in question?

**Comment by japel** [comment]
@jldugger no, I wasn't... Haven't tried running it as a daemon, but I will soon:
https://www.packtpub.com/mapt/book/networking-and-servers/9781785287947/1/ch01lvl1sec25/running-chef-client-as-a-daemon

**Comment by rmoriz** [comment]
The resource reads the certificate on each converge to check if the "days till expiration" criteria is met. 

There are many ways to deploy chef, usually you have a chef-server running (DIY hosting/cloud or as a service at https://manage.chef.io/login). When you provision your nodes in such a setup, by default, chef-client will run as a daemon and reconverge once or twice per hour (you can configure that).

If you use tools like knife-solo or knife-zero, which provide tooling around chef-solo and chef-zero, then you are responsible yourself for reconverging the nodes. If you think about it: each chef resource checks the current state before applying a change, so running chef on a regular interval is like an "integration test" of your production node. If something changes due to failure or manual intervention, chef is "healing" it automatically.

Most people of the recent Ansible bandwaggon don't get this concept and also the official let's encrypt client (now called certbot) does not get it: While it is responsible updating the certificates it does not ensure that your http is running as configured, it just violates the principle of the chef-server philosophy of "single source of truth". Certbot is mainly a tool for people who manually setup nodes (like all the tinkerers out there) but not for serious business/devops.
